### ISSUE TITLE
At the beginning of chapter 3, the "music" is crowd noise + car noises, even though the scene is inside and talking.

### ISSUE THREAD

**Issue by drojf** [07th-mod/matsuribayashi#12]
The problem: At the beginning of chapter 3, the "music" is loud ambient noise. Think crowd noise + car noises. Considering the scene is inside and talking to Irie that seems off.

The game: [Higurashi Ch.8]

The mod variant: [Full]

I bought the game at: [Steam]

My operating system is: [Windows]

I installed the patch: [Using the Installer]

Mod Install Date: [Yesterday]

State anything "special" about your computer's setup: nothing particularly special. Using a Dell Inspiron Gaming PC that's about 3 years old but it ran the rest of the Higurashi games fine.

**Comment by drojf** [comment]
Some replies from discord:

Person A
> Hmm, I’m pretty sure I remember that scene and it does have the car noise. I thought it was just supposed to be bustling city noise or something like that.

Person B
> Yea i remember the same

**Comment by KBD20** [comment]
I checked my original copy of kai and the background noise is the same.

**Comment by drojf** [comment]
Thanks KBD20.

Well, I'll close this now, but if someone disagrees feel free to reopen it.
