### ISSUE TITLE
Problems with voice acting

### ISSUE THREAD

**Issue by vdartsabvile** [07th-mod/matsuribayashi#50]
## Bug Information

**Describe the bug**:  I installed a full patch with the Russian language and faced the problem that some dialogues are without voice acting. Everything was fine in the previous parts. I reinstalled this part several times, with different settings, but nothing has changed. There may be problems in the script itself or the voice files.

## Install Information

**The game**: You should only report Higurashi Ch.8 related issues in this repository.

**The mod variant**: Full

**I installed the patch**: Using the Installer

**I bought the game at**: Steam

**Mod Install Date**: 09/05/2024

## System Information

**My operating system is**: Windows 11

**State anything "special" about your computer's setup**: My PC r5 4500 and rtx 3050

**Comment by drojf** [comment]
Have you tried contacting the Russian language patch author? See https://github.com/wf1264/matsuribayashi-ru (if it's a bug specific to the Russian patch).

Also, when you contact either them or us, it would be useful to provide a screenshot of the text which has no voice, or to type out the text, so we can find it in the script.

Please note that some lines/sections may have no voices, as there exist no voice files for some parts of the game. But if it seems unusual/unexpected then it may be an actual bug.
