### ISSUE TITLE
Steam Linux version loops back to "Opening may contain spoilers" option then back to the main menu on a chapter transition  [Needs Confirmation]

### ISSUE THREAD

**Issue by drojf** [07th-mod/matsuribayashi#9]
We had this report via discord:

> Steam Linux version seems to be looping back to "Opening may contain spoilers" option then back to the main menu on a chapter transition :thinking:

> Yea, seems to be happening on fresh install, fresh mod, fresh save where there normally would be a "tips" section

> Tested on Windows, behaviour is normal (I reach a "TIPS" screen chapter transition)
Tested on a different Linux box with the same result, "OP may contain spoilers" dialogue followed by looping back to main menu screen

The user tested on two linux machines, so perhaps confirmation isn't needed, but it would be pretty easy to reproduce if you're trying to fix it.

**Comment by drojf** [comment]
We had another user on Mac with a similar issue:

> Matsuribayashi is looping back to the main menu after Chapter 2, and there doesn't appear to be a way to progress; have tried an entirely fresh install, same issue.

> Higurashi Ch.8

> Full Install

> Steam Ver.

> MacOS

> Using the Installer

> Today

----

> I'm not getting the Opening may contain spoilers dialogue but otherwise the issue is the same

**Comment by Kamil689** [comment]
Same issue here on Linux, after `_mats_002` it looped back to the opening logos.

The game: Higurashi Ch.8

The mod variant: Full

I bought the game at: Steam

My operating system is: Linux

I installed the patch: Using the Installer

Mod Install Date: Today

Log after the problem happened: [Player.log](https://github.com/07th-mod/matsuribayashi/files/4908103/Player.log)

**Comment by idealpersona** [comment]
This appears to be related to achievements. I tested this with a player and was surprised to find that fixing a hard-coded Windows path resolved the problem.  I was surprised because this was present in minagoroshi as well and seems to have come from the vanilla game (but who knows what build stage things happened there).  But there was a full unity version upgrade within matsuri's release lifetime as well, so maybe the old unity version or just minagoroshi itself for whatever reason didn't have any restarts when faced with this issue on mac/linux. Either way, committed https://github.com/07th-mod/higurashi-assembly/commit/e73ee6dfc3563677fef7776daccabab4019295f3 and merged to matsuri.

@tellowkrinkle not sure if you have any input on this.

**Comment by ars-magna** [comment]
> This appears to be related to achievements. I tested this with a player and was surprised to find that fixing a hard-coded Windows path resolved the problem. I was surprised because this was present in minagoroshi as well and seems to have come from the vanilla game (but who knows what build stage things happened there). But there was a full unity version upgrade within matsuri's release lifetime as well, so maybe the old unity version or just minagoroshi itself for whatever reason didn't have any restarts when faced with this issue on mac/linux. Either way, committed [07th-mod/higurashi-assembly@e73ee6d](https://github.com/07th-mod/higurashi-assembly/commit/e73ee6dfc3563677fef7776daccabab4019295f3) and merged to matsuri.
> 
> @tellowkrinkle not sure if you have any input on this.

Building that with those changes does appear to fix the issue for me on Linux, progression is now possible. Cheers.

![](https://i.imgur.com/4hqq57B.jpg)

**Comment by bl4ckout31** [comment]
Using the latest `Assembly-CSharp.dll` for Matsuribayashi fixed the issue for me too. 
Tested on the first chapter transition, also on Linux.

**Comment by drojf** [comment]
I'm gonna close this one as it's been 2 years without issue being reported.
